
  utils:
    build:
      context: ../..
      dockerfile: infrastructure/docker/Dockerfile.utils
    container_name: utils
    networks: [fraud_net]
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - ../../:/app
    # Keep container running so we can exec into it
    command: tail -f /dev/null
